name: Build CI

on:
  workflow_dispatch: # 手动触发

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SSH_ACTIONS: "true"

    steps:
    - uses: actions/checkout@v4

    - run: sudo bash -c 'bash <(curl -s https://build-scripts.immortalwrt.org/init_build_environment.sh)'
    - run: ./scripts/feeds update -a
    - run: ./scripts/feeds install -a
    - run: make -j$(nproc)

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: release
        path: bin/targets/**/*.bin
